name=ArduinoLinkPLC
version=1.0.0
author=De_ice47
maintainer=De_ice47 <de_ice47.cross316@passinbox.com>
sentence= Provides a way to easily transport data between a microcontroller and a target network
paragraph= Provides a way to easily transport data between a microcontroller and a target network
category=Signal Input/Output
url=https://github.com/De-ice47/ArduinoLinkPLC
architectures=*
includes=ArduinoLinkPLC
license=MIT-0