name=ArduinoLinkPLC
version=1.0.0
author=De_ice47
maintainer=De_ice47 <de_ice47.cross316@passinbox.com>
sentence= Lightweight WiFi communication bridge for Arduino devices to interface with Unity applications.
paragraph= Lightweight WiFi communication bridge for Arduino devices to interface with Unity applications.
category=Signal Input/Output
url=https://github.com/De-ice47/ArduinoLinkPLC
architectures=*
includes=ArduinoLinkPLC
license=MIT-0